version: '3.1'

services:
  mongo:
    image: mongo
    restart:
      on-failure
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./migrations/:/docker-entrypoint-initdb.d/
      - ./docker/mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart:
      on-failure
    depends_on:
      - mongo
    ports:
      - "${MONGO_UI_PORT}:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/

  app:
    image: auth/app
    build:
      dockerfile: ./Dockerfile
      args:
        APP_PORT: ${APP_PORT}
    depends_on:
      - mongo
    restart:
      on-failure
    ports:
      - "${APP_PORT}:${APP_PORT}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${APP_PORT}/health/check" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
