version: '3.1'

services:
  redis:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - redis-network
    environment:
      - REDIS_DATABASES=16

  redis-commander:
    image: rediscommander/redis-commander:latest
    platform: linux/amd64
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - "${REDIS_UI_PORT}:8081"
    networks:
      - redis-network
    depends_on:
      - redis

networks:
  redis-network:
    driver: bridge
