version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart:
      on-failure
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    volumes:
      - ./docker/rabbitmq_data:/data